// import { course } from './course';

export const courseList: any[] = [
  {
    Id: 1,
    courseType: 'primary',
    courseFramework: 'Competancy 1',
    Time: '30 min',
    courseName: 'DA',
    Update: 'Updated 21 Jan 2020',
  },
  {
    Id: 2,
    courseType: 'error',
    courseFramework: 'Competancy 2',
    Time: '90 min',
    courseName: 'DA',
    Update: 'Updated 25 Jan 2020',
  },
  {
    Id: 3,
    courseType: 'warning',
    courseFramework: 'Competancy 3',
    Time: '30 min',
    courseName: 'DA',
    Update: 'Updated 30 Jan 2020',
  },
  {
    Id: 4,
    courseType: 'accent',
    courseFramework: 'Competancy 4',
    Time: '50 min',
    courseName: 'DA',
    Update: 'Updated 01 Feb 2020',
  },
  {
    Id: 5,
    courseType: 'primary',
    courseFramework: 'Competancy 5',
    Time: '120 min',
    courseName: 'DA',
    Update: 'Updated 15 Feb 2020',
  },
  {
    Id: 6,
    courseType: 'warning',
    courseFramework: 'Competancy 6',
    Time: '60 min',
    courseName: 'DA',
    Update: 'Updated 16 Feb 2020',
  },
  // {
  //   Id: 7,
  //   courseType: 'primary',
  //   courseFramework: 'competancy 7',
  //   Time: '90 min',
  //   courseName: 'DA',
  //   Update: 'Updated 18 Feb 2020',
  // },
  // {
  //   Id: 8,
  //   courseType: 'error',
  //   courseFramework: 'Angular',
  //   Time: '150 min',
  //   courseName: 'Basics of Angular',
  //   Update: 'Updated 20 Feb 2020',
  // },
  // {
  //   Id: 9,
  //   courseType: 'accent',
  //   courseFramework: 'Design',
  //   Time: '80 min',
  //   courseName: 'PSD to HTML From Scratch',
  //   Update: 'Updated 21 Feb 2020',
  // },
];
