name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # Hoặc nhánh mà bạn muốn tự động hóa

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build Docker image
      run: |
        docker build -t haupham2311/elearning-fe-d:latest .

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: haupham2311
        password: Hau@12345

    - name: Push Docker image
      run: |
        docker push haupham2311/elearning-fe-d:latest